name: Infrastructure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-scan:
    name: "Validate & Security Scan"
    runs-on: k3s-runner

    env:
      TF_VAR_github_pat: ${{ secrets.TF_VAR_GITHUB_PAT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0
          terraform_wrapper: false 

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Run Trivy IaC Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
